### ISSUE TITLE
loooong latency

### ISSUE THREAD

**Issue by vossilius** [qdm12/dns#39]
I am experiencing long ping times using the service. When I ping 1.1.1.1 (no TLS) on the host or within the container, times are usually below 30ms. Pi-hole, however, reports 100 to even 1000ms. Is what I measure the trade off of using 'over TLS'?

**Comment by qdm12** [comment]
Try a standard test on [dnsleaktest.com](https://www.dnsleaktest.com) and it'll tell you where the dns servers are located. Maybe the dns over tls servers are located far away from your location? My resolution is pretty much instantaneous (based in Montreal using Cloudflare+Google+Quad9)

**Comment by vossilius** [comment]
I did. In all test cases the next Cloudflare Server is 500 km away.

**Comment by qdm12** [comment]
That should be fine; is it slow for other providers too like Google? I'll check my pihole and report back what I get.

**Comment by qdm12** [comment]
Can you please try and post back results for:

```sh
# Using cloudflare dns over tls container
docker run -it --rm alpine:3.11 sh -c 'apk add bind-tools && time dig github.com'
```

and then the same thing using the plaintext dns 1.1.1.1

```sh
docker run -it --rm --dns 1.1.1.1 alpine:3.11 sh -c 'apk add bind-tools && time dig github.com'
```

I get 116ms vs 8ms as well, so there is indeed quite some overhead using Unbound and dns over tls (more negotiations and it goes over tcp instead of udp I guess). Although not 1 second of latency.

**Comment by vossilius** [comment]
Hi,

Thanks for your message.

```
...
;; Query time: 29 (42) msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Mon Jun 22 18:48:55 UTC 2020
;; MSG SIZE  rcvd: 65

real	0m 0.05s
user	0m 0.01s
sys	0m 0.00s
```
and direct
```
...
;; Query time: 27 (36) msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Mon Jun 22 18:49:19 UTC 2020
;; MSG SIZE  rcvd: 65

real	0m 1.05s
user	0m 0.03s
sys	0m 0.00s
```
The number in brackets is the first test, the other the second round. notice the 'real' figure. Any idea on this one?

As for your former question, I have two instances running. a) cloudflare, b) quad9. Both deliver similar results in Pi-hole.

**Comment by qdm12** [comment]
For me, on another device in my LAN, I get with DNS over TLS 55ms query time and 60ms real time; with plain DNS I have 15ms query time and 20ms real time.

From the numbers you get, it seems you take a long time to reach the container, but the container resolves the query quickly. Are you running the commands on the same host running this container?

**Comment by vossilius** [comment]
Yes, it's the same machine.

**Comment by qdm12** [comment]
So by `direct` you mean without the container? From what I see the query time is fine, it's about the real time (which might be unrelated to the container).

For me I get:

1. Using the container, first time: query time 12ms, real 0.01s
2. Using the container, subsequent times: query time (because of caching): 1ms, real: 0.00s
3. Using 1.1.1.1 directly, first and subsequent times: query time 15ms, real 0.02s

Now oddly dns over tls is faster than plaintext for whatever reason.

Can you post back 1, 2 and 3 using the docker run commands above to verify we are on the same page? Thanks.

**Comment by vossilius** [comment]
Hi, 

So sorry for my late reply. I ran into another issue on my machine causing some changes. Therefore, I am not very sure whether the setting has meanwhile changed.

My results:
1. 17ms; real 0,03s
2. 19ms; real 0,04s
3. 25ms; real 0.04s and 24ms; 0.04s

As you can see, the 'real' time dropped sharply (that's why I think the settings changed). Yet, the times shown in Pi-hole are still a couple of hundred ms. Weird.

Anyway, I think we can close the issue for now until I have figured out what made the numbers drop after my messing around.

Thanks for your support!

**Comment by qdm12** [comment]
Hi thanks for getting back! No problem for the late answer, I was late answering back too! 😄 

Great that the real time went down. I need to re-setup pihole on my side too, I'll check if it gives similar results.

We can keep the issue opened for now so I don't forget essentially 😉

**Comment by stumpylog** [comment]
I'm afraid it doesn't contribute much, but I also see sometimes long latency, particularly on the first query.  Subsequent queries must hit the cache and are near instant.  I see on the range of ~100 to 300+ milliseconds (per the pi-hole query log).

I'm running pi-hole directly on the host, looping back to this container with `127.0.0.1#5350`.  Both run on a raspberry pi, connected over Ethernet.

If there are tests or checks I can run to help, happy to experiment.

**Comment by qdm12** [comment]
Hello everyone, I'll start implementing my own dns over https client+dns server this weekend to solve the problem altogether (i need it for another repo as well), and drop Unbound which is still stuck on dns over tls. Hopefully I should be done this weekend.

**Comment by qdm12** [comment]
Unbound added recently support for DNS over HTTPs so that's good.

Although I'm almost done with https://github.com/qdm12/dns/pull/58 to add a DoT and DoH servers I wrote from scratch. I think another week should do it. I'd be curious to see if there is an improvement 😉

**Comment by qdm12** [comment]
You can run `qmcgaw/dns:v2.0.0-beta` right now. Documentation is on the `v2.0.0-beta` branch, and you can run DoT or DoH. It also has a bunch of fun features like Prometheus metrics.

It's quite stable, although I'm still working to add support for DNSSEC (not really that needed with encrypted DNS imo but anyway), and I'm still improving the Golang API to be stable for the future (using semver v2.x.x).

I'll close the issue since all the Unbound DoT delay is about to be irrelevant.
