### ISSUE TITLE
DoT test returns false & How to test properly

### ISSUE THREAD

**Issue by ex0nuss** [qdm12/dns#90]
Hi,

thanks for your work. Your image is super easy to set up!

I wanted to to test if DoT works properly. Therefore I used this website: https://tenta.com/test/?utm_source=blog (Section ADVANCED DNS LEAK TEST). 
Unfortunately it says that "TLS Enabled" is false. Now I am concerned if DoT works properly... 
I tried it both with v1 and v2 resulting in the same error.

Is there any way that I can test DoT?

Thanks in advance :)
Regards, Max

**Comment by qdm12** [comment]
Hi Max,

I checked the website and it gives the right Upstream DNS servers I'm using, and says DoT is off for me as well. It also says DNSSEC is enabled, although I didn't implement it in the v2 beta yet. My guess is, because your device is not directly using DoT (you use plaintext DNS to your DNS container which handles the encryption), it's not detected.

For the v1, I'm 99% sure DoT works and I'm 100% sure it works for the v2.0.0-beta since I coded it myself 😄 You could also try DoH on the v2.0.0-beta to see what happens.

Also maybe have a look at https://github.com/qdm12/dns#verify-dns-connection
